# -*- coding: utf-8 -*-
{
    'name': 'Hyper UI',
    'version': '13.0.1.0',
    'category': 'Studio',
    'description': u"""
This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.
""",
    'author': 'Grupo Salamander SAPI de CV',
    'depends': [
        'base',
    ],
    'data': [
        'data/assets.xml'
    ],
    'application': False,
    'license': 'OPL-1',
}
